### ISSUE TITLE
Pizza4 Micro Server (CM4 Edge Computer)

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/raspberry-pi-pcie-devices#136]
I just noticed the PIzza4 from a post on Twitter: https://www.openembed.com/products-list/13

![Ewj0K8VUUAAq3Aa](https://user-images.githubusercontent.com/481677/118682663-455c0c00-b7c6-11eb-9a10-1aacd8500f00.jpeg)

![Ewj0LPjUUAIA_3b](https://user-images.githubusercontent.com/481677/118682671-47be6600-b7c6-11eb-851f-04e68f596c27.jpeg)

![ExS44pmU8AEVGQk](https://user-images.githubusercontent.com/481677/118682687-4ab95680-b7c6-11eb-8d8c-6c423813837d.jpeg)

![EydGyrzWYAEMc0Q](https://user-images.githubusercontent.com/481677/118682706-4e4cdd80-b7c6-11eb-82de-7ccac442148f.jpeg)

![E1o9mExUcAEO2IP](https://user-images.githubusercontent.com/481677/118682721-50af3780-b7c6-11eb-9e90-7217242745d4.jpeg)

![E1E9FFgVUActUDC](https://user-images.githubusercontent.com/481677/118682731-51e06480-b7c6-11eb-9910-30661df9f946.jpeg)

It looks like it has:

  1. Dual Gigabit Ethernet (looks like it uses a Realtek PCIe chip for the 2nd slot)
  2. Built-in 3-way PCIe Switch ([PI7C9X2G404SV](https://ar.mouser.com/datasheet/2/115/PI7C9X2G404SV-Product-Brief-1536988.pdf))
  2. Dual full-size HDMI
  3. 1x M.2 M Key slot (full size)
  4. 1x M.2 A+E Key slot
  5. 2x USB (2.0? 3.0?)
  6. Custom designed enclosure
  7. USB Type-C for Power? OTG?

This is... a rather full-featured tiny board! I like it.

**Comment by YumingChang02** [comment]
I've received my unit!!
5. ~1x M.2 A+E Key slot~ the slot is a miniPCIe port (with PCIe gen2x1 and USB2)
6. 2x USB (2.0? 3.0?), its USB2 (seems to be powered off Microchip USB2514B, located between second Ethernet port and the stacked USB ports)
8. USB Type-C can both provide power and flash EMMC (haven't tested OTG yet), To flash onboard EMMC, there is a jumper around where the power button is on the PCB (the yellow jumper is also included in the box from seeed studio)
![1627639075809](https://user-images.githubusercontent.com/32900022/127637343-6acad3eb-089b-4033-8871-73984a73cc7f.jpg)
I got my unit with a black cover, which seems to be aluminum heatsink

* Issues found now
    * using openwrt with custom configurations [config.buildinfo](https://github.com/geerlingguy/raspberry-pi-pcie-devices/files/6906812/config.buildinfo.txt)
    * routing speed is around 8xx Mbps, however direct connection from PIzza to pfsense can go up to 9xx Mbps
        * PIzza <--[ switch ]--> pfsense : Wireguard speed can reach around 700Mbps via iperf3 single side
    * the MAC address of realtek 8111H seems odd ( showing 00:00:00:00:00:05 )

**Comment by mthird** [comment]
I finally got the 2nd NIC to work by updating to the latest nightly firmware using: `sudo rpi-update`!

**Comment by mthird** [comment]
Also, now that I realized there is no USB3 chip on board, putting the LTE modem into USB2 mode solved my remaining problem.

**Comment by AllizomFoxfire** [comment]
@mthird Well, I have two of these units on my desk now after thinking one was faulty. I had them send me another in exchange as I could only get it into RPI boot once. Immediately following that one instance a package arrived in which I had bought some new USB-C super-speed cables which absolutely do NOT work as OTG cables. I had no idea this was the case. It took me days to figure this out by pure trial and error.

Now I have properly changed the boot order to 0xf34516 to reflect the NVME  > emmc > USB storage > RPIBOOT failsafe > loop. The 4 and 5 are really interchangeable as there are no USB3 ports, and as you said, that is the one major shortcoming of this device as the bus exists since the second gigabit ethernet sits on it.

Otherwise, this is a fantastic little device that ticks every other box on the list of what I could want in a micro server.

**Comment by duckgogo** [comment]
@AllizomFoxfire I think Pizza 4 cannot boot from NVME, as it uses PCIe switch

**Comment by abin444** [comment]
Hey does anyone has the schematics for this board? Almost all details about this board seems to  have vanished. I'm more interested in the Pericom PCIe switch and the I210 ethernet controller implementation as I use this combinations for a CM5 based board. The intel IPS a/c creation has been dragging me for a few days.
