### ISSUE TITLE
Gpu on pi

### ISSUE THREAD

**Issue by groot4272** [geerlingguy/raspberry-pi-pcie-devices#33]
Please once try gpu once again on windows on cm4
As drivers are available and recently microsoft also announced x64 emulation on arm

**Comment by PixlRainbow** [comment]
He never stopped testing GPUs. It's a work in progress; see [these issues](/geerlingguy/raspberry-pi-pcie-devices/issues?q=is%3Aissue+is%3Aopen+label%3A%22currently+testing%22+GPU). He just hasn't gotten around to uploading any GPU videos yet since he hasn't got enough content to fill a video.

There are also other reasons he isn't testing with Windows on ARM at the moment, see #7

**Comment by geerlingguy** [comment]
Yes; thanks for opening the issue, and please follow those other issues for updates. Just installing Windows on the Pi (which isn't officially supported by Microsoft) is a project unto itself, and I don't think it will be the magic bullet here, as there are many other layers to unpack first.
